// Flat lucide-react re-exports under contextual names, same pattern as
// src/widgets/Chat/icons.tsx — no wrapping, pass size/color/strokeWidth as usual.
export {
  Folder as FilesFolderIcon,
  FolderOpen as FilesFolderOpenIcon,
  FolderPlus as FilesFolderPlusIcon,
  FolderInput as FilesDropboxIcon,
  FolderLock as FilesPersonalFolderIcon,
  File as FilesFileIcon,
  FileText as FilesPdfIcon,
  FileImage as FilesImageIcon,
  FileSpreadsheet as FilesSheetIcon,
  FileArchive as FilesArchiveIcon,
  FileVideo as FilesVideoIcon,
  FileAudio as FilesAudioIcon,
  FileType as FilesDocIcon,
  Search as FilesSearchIcon,
  Upload as FilesUploadIcon,
  Download as FilesDownloadIcon,
  Users as FilesUsersIcon,
  UserPlus as FilesShareIcon,
  Pencil as FilesRenameIcon,
  Trash2 as FilesDeleteIcon,
  X as FilesCloseIcon,
  ChevronRight as FilesChevronIcon,
  ChevronDown as FilesChevronDownIcon,
  Check as FilesCheckIcon,
  Crown as FilesVipIcon,
  HardDrive as FilesStorageIcon,
  Eye as FilesPreviewIcon,
  ExternalLink as FilesExternalIcon,
  MoreVertical as FilesMoreIcon,
  Image as FilesCoverIcon,
  Plus as FilesPlusIcon,
  Home as FilesHomeIcon,
  Command as FilesCommandIcon,
} from 'lucide-react'
