import '@/shared/scss/_variables.scss'
import '@/shared/scss/config/functions.scss'
import '@/shared/scss/config/keyframes.scss'
import '@/shared/scss/config/mixins.scss'
import '@/shared/scss/config/reset.scss'
import '@/shared/scss/config/root.scss'
import '@/shared/scss/main.scss'
import type { Metadata } from 'next'
import { NextIntlClientProvider } from 'next-intl'
import { getLocale, getMessages } from 'next-intl/server'
import { Roboto } from 'next/font/google'

const robotoSans = Roboto({
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-main'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const locale = await getLocale()
  const messages = await getMessages()
  return (
    <html lang={locale}>
      <body className={`${robotoSans.variable} `}>
        <NextIntlClientProvider messages={messages}>{children}</NextIntlClientProvider>
      </body>
    </html>
  )
}
