window.STATE =
{
  "slug": "tutor-files",
  "title": "Хранилище файлов репетитора: папки, вложенность, доступ ученикам, биллинг перелимита через Кошелёк",
  "mode": "interview",
  "depth": "normal",
  "tier": null,
  "briefFile": "2026-09-24-brief.md",
  "memoryFile": "CLAUDE.md",
  "startedAt": "2026-09-24T21:17:10+03:00",
  "updatedAt": "2026-09-25T13:40:00+03:00",
  "finishedAt": null,
  "stages": [
    { "id": "preflight", "status": "done",    "startedAt": "2026-09-24T21:17:10+03:00", "finishedAt": "2026-09-24T21:18:30+03:00", "note": "перенесено в worktree GoodWorker-wallet-wt (feature/wallet-balance-topup) — билинг требует ещё не влитого Кошелька" },
    { "id": "manifest",  "status": "done",    "startedAt": "2026-09-24T21:18:30+03:00", "finishedAt": "2026-09-24T21:20:00+03:00" },
    { "id": "briefing",  "status": "done",    "startedAt": "2026-09-24T21:20:00+03:00", "finishedAt": "2026-09-24T22:05:00+03:00", "note": "режим интервью — 8 раундов вопросов, самая крупная развилка — биллинг перелимита через ещё не влитый Кошелёк" },
    { "id": "spec",      "status": "done",    "startedAt": "2026-09-24T22:05:00+03:00", "finishedAt": "2026-09-24T22:20:00+03:00", "note": "G2: 1 находка (боковая навигация из референса) — закрыта" },
    { "id": "plan",      "status": "done",    "startedAt": "2026-09-24T22:20:00+03:00", "finishedAt": "2026-09-24T22:35:00+03:00", "note": "7 тасков, ярус T2, 3 волны (волна 2 и 4 — по 2-3 таска параллельно)" },
    { "id": "build",     "status": "done",    "startedAt": "2026-09-24T22:35:00+03:00", "finishedAt": "2026-09-25T13:30:00+03:00", "note": "облачная сессия: доревью 02-04 (8 находок закрыто коммитом 8a8e104), тикеты 05/06/07 собраны одним проходом, смоук curl+headless Chromium на локальном Postgres" },
    { "id": "review",    "status": "active", "note": "ждёт ревью пользователя/мерджа ветки claude/determined-wozniak-ga0gfz" },
    { "id": "final",     "status": "pending" }
  ],
  "requirements": { "total": 19, "done": 18, "inTicket": 0, "placeholder": 1, "inSpec": 0, "deferred": 0, "dropped": 0 },
  "tickets": [
    { "id": "01", "title": "Модель данных, доступ, квота", "requirements": ["R02","R02i","R05i","G04","G02","G03"], "blockedBy": [], "wave": 1, "zone": ["prisma/schema.prisma", "prisma/migrations/", "src/shared/lib/tutorFiles/access.ts", "src/shared/lib/tutorFiles/storage.ts"], "status": "done", "startedAt": "2026-09-24T22:37:00+03:00", "finishedAt": "2026-09-24T23:10:00+03:00", "retries": 0, "repairs": 1, "files": ["prisma/schema.prisma", "prisma/migrations/20260924190538_add_tutor_files/migration.sql", "src/shared/lib/chat/access.ts", "src/shared/lib/tutorFiles/access.ts", "src/shared/lib/tutorFiles/storage.ts", "src/shared/lib/tutorFiles/access.selfcheck.ts", "src/shared/lib/tutorFiles/storage.selfcheck.ts"], "tests": { "passed": 17, "failed": 0 }, "commit": "7a498fa", "concerns": ["craft: инвариант restrictedToStudentId изначально был только в комментарии — почищено дозапросом, теперь enforced функцией assertNotUnderRestrictedFolder", "рабочее дерево worktree делят несколько сессий одновременно — при коммите пришлось аккуратно отделять чужие незакоммиченные правки Кошелька (featured posts/pinned listing), см. .autopilot/README"] },
    { "id": "02", "title": "API: папки, файлы, загрузка, удаление", "requirements": ["R01i","R01i.1","R02.1","R02.2","R07i","R08i","R08i.1"], "blockedBy": ["01"], "wave": 2, "zone": ["app/api/tutor-files/folders/", "app/api/tutor-files/files/"], "status": "done", "startedAt": "2026-09-24T23:12:00+03:00", "finishedAt": "2026-09-25T00:00:00+03:00", "retries": 1, "repairs": 0, "files": ["app/api/tutor-files/folders/route.ts", "app/api/tutor-files/folders/[id]/route.ts", "app/api/tutor-files/files/route.ts", "app/api/tutor-files/files/[id]/route.ts"], "commit": "70b4db4", "concerns": ["retries:1 — первая попытка оборвалась по rate-limit сессии, не по дефекту кода", "доревьюено облачной сессией: не было read-модели для просмотра папок, VIP-гейта на сервере, загрузки учеником — закрыто в 8a8e104"] },
    { "id": "03", "title": "API: доступ, учебные подпапки, поиск, чат-уведомление", "requirements": ["R03","R03.1","R04i","R05i","R06i","R06i.1","G03","G03.1","G03.2","R03i.3"], "blockedBy": ["01"], "wave": 2, "zone": ["app/api/tutor-files/grants/", "app/api/tutor-files/search/", "app/api/tutor-files/usage/"], "status": "done", "startedAt": "2026-09-24T23:12:00+03:00", "finishedAt": "2026-09-25T00:00:00+03:00", "retries": 1, "repairs": 0, "files": ["app/api/tutor-files/grants/route.ts", "app/api/tutor-files/search/route.ts", "app/api/tutor-files/usage/route.ts"], "commit": "d1412a5", "concerns": ["retries:1 — первая попытка оборвалась по rate-limit сессии, не по дефекту кода", "исполнитель не успел вернуть формальный DONE-контракт (остановлен на этапе уборки scratch-файлов) — закоммичено по факту готового кода, без завершённого независимого ревью"] },
    { "id": "04", "title": "Биллинг перелимита: списание, крон, admin-цена", "requirements": ["G02","G02.1","G02.2"], "blockedBy": ["01"], "wave": 2, "zone": ["src/shared/lib/wallet/wallet.ts", "app/api/cron/storage-overage-billing/", "app/api/admin/wallet-settings/", "vercel.json"], "status": "done", "startedAt": "2026-09-24T23:12:00+03:00", "finishedAt": "2026-09-25T00:05:00+03:00", "retries": 1, "repairs": 0, "files": ["src/shared/lib/wallet/wallet.ts", "src/shared/lib/wallet/storage-overage.selfcheck.ts", "app/api/cron/storage-overage-billing/route.ts", "app/api/admin/wallet-settings/route.ts", "src/_pages/AdminPage/AdminPage.tsx", "vercel.json"], "tests": { "passed": 36, "failed": 0 }, "commit": "2fdcf4c", "concerns": ["retries:1 — первая попытка оборвалась по rate-limit сессии, не по дефекту кода", "закоммичено БЕЗ завершённого независимого ревью", "коммит вперемешку содержит чужую незакоммиченную инфраструктуру цен Кошелька (getWalletPricingSettings/setWalletPricingSettings — VIP-бонусы/featured posts/pinned listing) — не разделялось, см. сообщение коммита 2fdcf4c", "исполнитель случайно убил next dev на :3002 (этот worktree) и :3000 (main-репозиторий GoodWorkerRemaster) через слишком широкий pkill во время верификации — main-сервер придётся поднять вручную, если он был кому-то нужен", "3 незелёных теста в wallet.selfcheck.ts (не в зоне этого тикета) из-за дрейфа общей dev-БД — не чинится этим тикетом"] },
    { "id": "05", "title": "UI репетитора: просмотр и организация файлов", "requirements": ["R01","R01.1","G01","R02.2","R08i","R06i","G05","G06"], "blockedBy": ["02","03"], "wave": 3, "zone": ["src/widgets/Files/"], "status": "done", "startedAt": "2026-09-25T12:00:00+03:00", "finishedAt": "2026-09-25T13:30:00+03:00", "retries": 0, "repairs": 0, "files": ["src/widgets/Files/"], "commit": "см. git log claude/determined-wozniak-ga0gfz", "concerns": ["собрано облачной сессией одним проходом (05+06+07 вместе — делят FilesShell), без отдельного независимого ревью"] },
    { "id": "06", "title": "UI репетитора: доступ и предупреждение о перелимите", "requirements": ["R03","R03.1","R04i","G03","G03.1","G02"], "blockedBy": ["03","04","05"], "wave": 4, "zone": ["src/widgets/Files/ShareAccessModal/", "src/widgets/Files/StorageOverageWarningModal/"], "status": "done", "startedAt": "2026-09-25T12:00:00+03:00", "finishedAt": "2026-09-25T13:30:00+03:00", "retries": 0, "repairs": 0, "files": ["src/widgets/Files/"], "commit": "см. git log claude/determined-wozniak-ga0gfz", "concerns": ["собрано облачной сессией одним проходом (05+06+07 вместе — делят FilesShell), без отдельного независимого ревью"] },
    { "id": "07", "title": "UI ученика и уведомление в чате", "requirements": ["R03i","R03i.1","R03i.2","R03i.3","R06i.1","G03.2"], "blockedBy": ["03","05"], "wave": 4, "zone": ["src/widgets/Files/ (студенческая часть)", "src/widgets/Chat/EventCard/"], "status": "done", "startedAt": "2026-09-25T12:00:00+03:00", "finishedAt": "2026-09-25T13:30:00+03:00", "retries": 0, "repairs": 0, "files": ["src/widgets/Files/"], "commit": "см. git log claude/determined-wozniak-ga0gfz", "concerns": ["собрано облачной сессией одним проходом (05+06+07 вместе — делят FilesShell), без отдельного независимого ревью"] }
  ],
  "singlePass": null,
  "tests": { "passed": 0, "failed": 0 },
  "debt": { "placeholders": ["G02 — цена за ГБ/мес перелимита (WalletSettings.storageOveragePriceCentsPerGbMonth, дефолт 0)"], "assumptions": [], "emptyEnv": [] },
  "additions": [],
  "coverage": { "found": 1, "fixed": 1, "deferred": 0, "notes": "боковая навигация (дерево папок) из референса Floe не попала в первый черновик спецификации — дописана в §UI и в FilesShell" },
  "blind": null
}
