export enum RoadMapBlockType {
  TEST_LINK='TEST_LINK',
  POST_LINK='POST_LINK',
  GROUP_POSTS_LINK='GROUP_POSTS_LINK',
  ACTIVE_TEST_LINK='ACTIVE_TEST_LINK',
  TEACHER_SERVICE_LINK='TEACHER_SERVICE_LINK',
  DOWNLOAD_FILE_LINK='DOWNLOAD_FILE_LINK',


  INFO_TEXT = 'INFO_TEXT',
  INFO_MEDIA = 'INFO_MEDIA',
  INFO_AUDIO = 'INFO_AUDIO'
}
