ALTER TABLE "Service" ADD COLUMN IF NOT EXISTS "targetStudentId" TEXT;
ALTER TABLE "Service" ADD COLUMN IF NOT EXISTS "isPersonal" BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE "Service" ADD CONSTRAINT IF NOT EXISTS "Service_targetStudentId_fkey" FOREIGN KEY ("targetStudentId") REFERENCES "Student"("id") ON DELETE SET NULL ON UPDATE CASCADE;
